# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{repertoire_core}
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher York"]
  s.date = %q{2009-12-03}
  s.description = %q{RepertoireCore provides registration and role based authorization to Repertoire projects}
  s.email = %q{yorkc@mit.edu}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "FAQ",
     "INSTALL",
     "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION",
     "app/controllers/application.rb",
     "app/controllers/memberships.rb",
     "app/controllers/users.rb",
     "app/helpers/application_helper.rb",
     "app/helpers/memberships_helper.rb",
     "app/mailers/user_mailer.rb",
     "app/mailers/views/layout/core.text.erb",
     "app/mailers/views/user_mailer/activation.text.erb",
     "app/mailers/views/user_mailer/approve.text.erb",
     "app/mailers/views/user_mailer/deny.text.erb",
     "app/mailers/views/user_mailer/grant.text.erb",
     "app/mailers/views/user_mailer/password_reset_key.text.erb",
     "app/mailers/views/user_mailer/request.text.erb",
     "app/mailers/views/user_mailer/signup.text.erb",
     "app/models/membership.rb",
     "app/models/role.rb",
     "app/views/README",
     "app/views/_memberships_table.html.erb",
     "app/views/_user_detail.html.erb",
     "app/views/exceptions/unauthenticated.html.erb",
     "app/views/layout/core.html.erb",
     "app/views/memberships/edit.html.erb",
     "app/views/memberships/grant.html.erb",
     "app/views/memberships/index.html.erb",
     "app/views/memberships/subscribe.html.erb",
     "app/views/users/edit.html.erb",
     "app/views/users/forgot_password.html.erb",
     "app/views/users/index.html.erb",
     "app/views/users/new.html.erb",
     "app/views/users/requests.html.erb",
     "app/views/users/reset_password.html.erb",
     "config/fixtures.rb",
     "config/init.rb",
     "config/router.rb",
     "lib/repertoire_core.rb",
     "lib/repertoire_core/exceptions.rb",
     "lib/repertoire_core/merbtasks.rb",
     "lib/repertoire_core/mixins/authorization_helper.rb",
     "lib/repertoire_core/mixins/dm/resource_mixin.rb",
     "lib/repertoire_core/mixins/user_authorization_mixin.rb",
     "lib/repertoire_core/mixins/user_mixin.rb",
     "lib/repertoire_core/mixins/user_properties_mixin.rb",
     "lib/repertoire_core/slicetasks.rb",
     "lib/repertoire_core/spectasks.rb",
     "public/images/rep.core/gravatar.png",
     "public/images/rep.core/hyperstudio.jpg",
     "public/javascripts/README",
     "public/javascripts/rep.core.js",
     "public/stylesheets/README",
     "public/stylesheets/rep.core.css",
     "public/stylesheets/rep.core.membership.css",
     "spec/controllers/authorization_helper_spec.rb",
     "spec/controllers/memberships_spec.rb",
     "spec/controllers/users_spec.rb",
     "spec/mailers/user_mailer_spec.rb",
     "spec/models/role_spec.rb",
     "spec/models/user_spec.rb",
     "spec/repertoire_core_spec.rb",
     "spec/spec_helper.rb",
     "spec/spec_helpers/helpers.rb",
     "spec/spec_helpers/valid_model_hashes.rb",
     "stubs/app/controllers/users.rb"
  ]
  s.homepage = %q{http://github.com/repertoire/repertoire-core}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{RepertoireCore provides registration and role based authorization to Repertoire projects}
  s.test_files = [
    "spec/controllers/authorization_helper_spec.rb",
     "spec/controllers/memberships_spec.rb",
     "spec/controllers/users_spec.rb",
     "spec/mailers/user_mailer_spec.rb",
     "spec/models/role_spec.rb",
     "spec/models/user_spec.rb",
     "spec/repertoire_core_spec.rb",
     "spec/spec_helper.rb",
     "spec/spec_helpers/helpers.rb",
     "spec/spec_helpers/valid_model_hashes.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rep.ajax.toolkit>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<rep.jquery>, [">= 1.3.2"])
      s.add_runtime_dependency(%q<merb-mailer>, [">= 1.0.15"])
      s.add_runtime_dependency(%q<merb-assets>, [">= 1.0.15"])
      s.add_runtime_dependency(%q<merb-action-args>, [">= 1.0.15"])
      s.add_runtime_dependency(%q<merb-auth-core>, [">= 1.0.15"])
      s.add_runtime_dependency(%q<merb-auth-more>, [">= 1.0.15"])
      s.add_runtime_dependency(%q<merb-auth-slice-password>, [">= 1.0.15"])
      s.add_runtime_dependency(%q<merb-helpers>, [">= 1.0.15"])
      s.add_runtime_dependency(%q<merb-slices>, [">= 1.0.15"])
      s.add_runtime_dependency(%q<dm-core>, [">= 0.10.1"])
      s.add_runtime_dependency(%q<dm-validations>, [">= 0.10.1"])
      s.add_runtime_dependency(%q<dm-timestamps>, [">= 0.10.1"])
      s.add_runtime_dependency(%q<dm-aggregates>, [">= 0.10.1"])
      s.add_runtime_dependency(%q<dm-is-nested_set>, [">= 0.10.1"])
      s.add_runtime_dependency(%q<dm-is-list>, [">= 0.10.1"])
      s.add_runtime_dependency(%q<tlsmail>, ["= 0.0.1"])
    else
      s.add_dependency(%q<rep.ajax.toolkit>, [">= 0.1.1"])
      s.add_dependency(%q<rep.jquery>, [">= 1.3.2"])
      s.add_dependency(%q<merb-mailer>, [">= 1.0.15"])
      s.add_dependency(%q<merb-assets>, [">= 1.0.15"])
      s.add_dependency(%q<merb-action-args>, [">= 1.0.15"])
      s.add_dependency(%q<merb-auth-core>, [">= 1.0.15"])
      s.add_dependency(%q<merb-auth-more>, [">= 1.0.15"])
      s.add_dependency(%q<merb-auth-slice-password>, [">= 1.0.15"])
      s.add_dependency(%q<merb-helpers>, [">= 1.0.15"])
      s.add_dependency(%q<merb-slices>, [">= 1.0.15"])
      s.add_dependency(%q<dm-core>, [">= 0.10.1"])
      s.add_dependency(%q<dm-validations>, [">= 0.10.1"])
      s.add_dependency(%q<dm-timestamps>, [">= 0.10.1"])
      s.add_dependency(%q<dm-aggregates>, [">= 0.10.1"])
      s.add_dependency(%q<dm-is-nested_set>, [">= 0.10.1"])
      s.add_dependency(%q<dm-is-list>, [">= 0.10.1"])
      s.add_dependency(%q<tlsmail>, ["= 0.0.1"])
    end
  else
    s.add_dependency(%q<rep.ajax.toolkit>, [">= 0.1.1"])
    s.add_dependency(%q<rep.jquery>, [">= 1.3.2"])
    s.add_dependency(%q<merb-mailer>, [">= 1.0.15"])
    s.add_dependency(%q<merb-assets>, [">= 1.0.15"])
    s.add_dependency(%q<merb-action-args>, [">= 1.0.15"])
    s.add_dependency(%q<merb-auth-core>, [">= 1.0.15"])
    s.add_dependency(%q<merb-auth-more>, [">= 1.0.15"])
    s.add_dependency(%q<merb-auth-slice-password>, [">= 1.0.15"])
    s.add_dependency(%q<merb-helpers>, [">= 1.0.15"])
    s.add_dependency(%q<merb-slices>, [">= 1.0.15"])
    s.add_dependency(%q<dm-core>, [">= 0.10.1"])
    s.add_dependency(%q<dm-validations>, [">= 0.10.1"])
    s.add_dependency(%q<dm-timestamps>, [">= 0.10.1"])
    s.add_dependency(%q<dm-aggregates>, [">= 0.10.1"])
    s.add_dependency(%q<dm-is-nested_set>, [">= 0.10.1"])
    s.add_dependency(%q<dm-is-list>, [">= 0.10.1"])
    s.add_dependency(%q<tlsmail>, ["= 0.0.1"])
  end
end

